name: 'Docker Compose Action'
description: 'GitHub Action to run Docker Compose'
inputs:
  input-file:
    description: 'my imput file'
    required: true
    default: 'input_text.txt'
  output-file:
    description: 'my output file'
    required: true
    default: 'output_corect.txt'

runs:
  using: 'docker'
  #image: 'docker:latest'  
  image: 'Dockerfile'  
  args:
    - ${{  inputs.input-file }}
    - ${{  inputs.output-file }}
