name: task2

on:
  push:
    branches:
      - main


jobs:
  test_task2:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: unzip file
        run:  unzip UsermanagmentWeb.zip
      - name: install ngrok
        run: |
          sudo apt install unzip
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          sudo mv ngrok /usr/local/bin
          ngrok --version
      - name: npm install
        working-directory: ./UsermanagmentWeb
        run: |
          npm install
          npm run dev    
          ngrok http http://localhost:8080
    
