name: task2

on:
  push:
    branches:
      - main


jobs:
  test_task2:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: unzip file
        run: unzip UsermanagmentWeb.zip
      - name: ip adres
        run: ifconfig
      - name: npm install
        working-directory: ./UsermanagmentWeb
        run: |
          npm install
          npm run dev
