name: task2

on:
  push:
    branches:
      - main


jobs:
  test_task2:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: unzip file
        run: unzip UsermanagmentWeb.zip
      - name: list dir
        run: |
          cd UsermanagmentWeb
          ls -la
