name: task2

on:
  push:
    branches:
      - main


jobs:
  test_task2:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: unzip file
        run:  unzip UsermanagmentWeb.zip
      - name: npm install
        working-directory: ./UsermanagmentWeb
        run: |
          npm install
          brew install ngrok/ngrok/ngrok
          ngrok config add-authtoken 2oF7adWYtidDVIRKYkfoAISpOwi_7cemDNx7xCmdMZsRdg9Qb
          npm run dev    
          ngrok http http://localhost:8080
    
