name: Run Docker Compose Action

on:
  push:
    branches:
      - main 

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: list dir 
        run: |
          cd 5_Text_spelling_checker
          ls -la

      - name: Run Docker Compose Action
        uses: ./
